# Generated by Django 5.1.1 on 2024-10-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico_cursado', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Especialidad', 'Especialidad'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado')], default='Licenciatura', max_length=12)),
                ('programa_academico_cursado', models.CharField(max_length=100)),
                ('institucion_donde_curso', models.CharField(max_length=255)),
                ('estado_institucion', models.CharField(max_length=100)),
                ('fecha_graduacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColegioProfesoresPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_colegio_profesores', models.CharField(max_length=255)),
                ('nombre_sesion', models.CharField(max_length=255)),
                ('numero_sesion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosAcademicosAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_academica_actual', models.CharField(max_length=100)),
                ('nom_programa_actual', models.CharField(max_length=100)),
                ('estatus', models.CharField(choices=[('Completo', 'Tiempo Completo'), ('Parcial', 'Tiempo Parcial')], default='Completo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DatosAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonalesAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'H'), ('M', 'M')], default=None, max_length=1, null=True)),
                ('correo_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_2', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('unidad_aprendizaje', models.CharField(max_length=100)),
                ('creditos', models.FloatField()),
                ('periodo', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('lugar_realizacion', models.CharField(max_length=255)),
                ('total_creditos', models.FloatField()),
                ('fecha_limite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('unidad_aprendizaje', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('lugar_realizacion', models.CharField(default='ESCOM', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaProgramaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('firma_alumno', models.BooleanField()),
                ('firma_asesor', models.BooleanField()),
                ('firma_jefe', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosasesor')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
        ),
        migrations.CreateModel(
            name='ActaRevisionTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tesis', models.CharField(max_length=255)),
                ('porcentaje_plagio', models.FloatField()),
                ('conclusion_plagio', models.TextField()),
                ('justificacion_conclusion', models.TextField()),
                ('manifiesto_comision', models.TextField(choices=[('Aprobar', 'Aprobar'), ('Susperder', 'Suspender'), ('No Aprobar', 'No Aprobar')], max_length=10)),
                ('firma_comision_1', models.BooleanField()),
                ('firma_comision_2', models.BooleanField()),
                ('firma_comision_3', models.BooleanField()),
                ('firma_presidente_colegio', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
        ),
        migrations.CreateModel(
            name='ActaRegistroTemaTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_tesis', models.CharField(max_length=255)),
                ('objetivo_general_tesis', models.TextField()),
                ('nombre_director_1', models.CharField(max_length=100)),
                ('nombre_director_2', models.CharField(blank=True, max_length=100, null=True)),
                ('aplicacion_director', models.BooleanField()),
                ('base_tesis', models.TextField()),
                ('firma_director_1', models.BooleanField()),
                ('firma_director_2', models.BooleanField(blank=True, null=True)),
                ('firma_alumno', models.BooleanField()),
                ('firma_presidente_colegio', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_constancia_programa_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.constanciaprogramaindividual')),
                ('id_programa_actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.programaactividades')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_alumno', models.BooleanField(blank=True, null=True)),
                ('firma_asesor', models.BooleanField(blank=True, null=True)),
                ('firma_jefe', models.BooleanField(blank=True, null=True)),
                ('aviso_privacidad', models.BooleanField(blank=True, null=True)),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_programa_semestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.programasemestral')),
                ('id_solicitud_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.solicitudinscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionAntecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_antecedentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.antecedentesacademicos')),
                ('id_solicitud_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.solicitudinscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
                ('semestre_a_cursar', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('requiere_unidad', models.BooleanField()),
                ('firma_alumno', models.BooleanField()),
                ('firma_asesor', models.BooleanField()),
                ('firma_jefe', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
        ),
        migrations.CreateModel(
            name='ReinscripcionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_programa_semestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.programasemestral')),
                ('id_solicitud_reinscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.solicitudreinscripcion')),
            ],
        ),
    ]
