# Generated by Django 5.1.1 on 2024-10-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico_cursado', models.CharField(max_length=100)),
                ('programa_academico_cursado', models.CharField(max_length=100)),
                ('institucion_donde_curso', models.CharField(max_length=255)),
                ('estado_institucion', models.CharField(max_length=100)),
                ('fecha_graduacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ColegioProfesoresPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_colegio_profesores', models.CharField(max_length=255)),
                ('nombre_sesion', models.CharField(max_length=255)),
                ('numero_sesion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosAcademicosAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.CharField(max_length=50)),
                ('unidad_academica_actual', models.CharField(max_length=100)),
                ('nom_programa_actual', models.CharField(max_length=100)),
                ('estatus', models.CharField(choices=[('C', 'Tiempo Completo'), ('P', 'Tiempo Parcial'), ('O', 'Otro')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DatosAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('firma_asesor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonalesAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=255)),
                ('telefono_casa', models.CharField(max_length=20)),
                ('telefono_movil', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=10)),
                ('correo_1', models.EmailField(max_length=254)),
                ('correo_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('firma_alumno', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('unidad_aprendizaje', models.CharField(max_length=100)),
                ('creditos', models.FloatField()),
                ('periodo', models.CharField(max_length=50)),
                ('lugar_realizacion', models.CharField(max_length=255)),
                ('total_creditos', models.FloatField()),
                ('fecha_limite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('unidad_aprendizaje', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('lugar_realizacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActaRevisionTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tesis', models.CharField(max_length=255)),
                ('porcentaje_plagio', models.FloatField()),
                ('conclusion_plagio', models.TextField()),
                ('justificacion_conclusion', models.TextField()),
                ('manifiesto_comision', models.TextField()),
                ('firma_comision_1', models.BooleanField()),
                ('firma_comision_2', models.BooleanField()),
                ('firma_comision_3', models.BooleanField()),
                ('firma_presidente_colegio', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
        ),
        migrations.CreateModel(
            name='ActaRegistroTemaTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_tesis', models.CharField(max_length=255)),
                ('objetivo_general_tesis', models.TextField()),
                ('nombre_director_1', models.CharField(max_length=100)),
                ('nombre_director_2', models.CharField(blank=True, max_length=100, null=True)),
                ('aplicacion_director', models.BooleanField()),
                ('base_tesis', models.TextField()),
                ('firma_director_1', models.BooleanField()),
                ('firma_director_2', models.BooleanField(blank=True, null=True)),
                ('firma_alumno', models.BooleanField()),
                ('firma_presidente_colegio', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaProgramaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_alumno', models.BooleanField()),
                ('firma_asesor', models.BooleanField()),
                ('firma_jefe', models.BooleanField()),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosasesor')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
                ('programa_semestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.programasemestral')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_alumno', models.BooleanField()),
                ('firma_asesor', models.BooleanField()),
                ('firma_jefe', models.BooleanField()),
                ('aviso_privacidad', models.BooleanField()),
                ('antecedentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.antecedentesacademicos')),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
                ('programa_semestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.programasemestral')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nom_programa_a_cursar', models.CharField(max_length=100)),
                ('unidad_academica_a_cursar', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('semestre_a_cursar', models.CharField(max_length=10)),
                ('requiere_unidad', models.BooleanField()),
                ('firma_alumno', models.BooleanField()),
                ('firma_asesor', models.BooleanField()),
                ('firma_jefe', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
                ('programa_semestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.programasemestral')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_solicitud', models.TextField()),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.tiposolicitud')),
            ],
        ),
    ]
