# Generated by Django 5.1.3 on 2025-01-03 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico_cursado', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Especialidad', 'Especialidad'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado')], default='Licenciatura', max_length=12)),
                ('programa_academico_cursado', models.CharField(max_length=100)),
                ('institucion_donde_curso', models.CharField(default='ESCOM', max_length=255)),
                ('estado_institucion', models.CharField(max_length=100)),
                ('fecha_graduacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tabla de Antecedentes Académicos',
                'verbose_name_plural': 'Tabla de Antecedentes Académicos',
            },
        ),
        migrations.CreateModel(
            name='ColegioProfesoresPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_colegio_profesores', models.CharField(max_length=255)),
                ('nombre_sesion', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_sesion', models.IntegerField(blank=True, null=True)),
                ('fecha_sesion', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Tabla del colegio de profesores',
                'verbose_name_plural': 'Tabla del colegio de profesores',
            },
        ),
        migrations.CreateModel(
            name='ProgramaActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('unidad_aprendizaje', models.CharField(max_length=100)),
                ('creditos', models.FloatField()),
                ('periodo', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('lugar_realizacion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tabla del programa de actividades',
                'verbose_name_plural': 'Tabla del programa de actividades',
            },
        ),
        migrations.CreateModel(
            name='DatosAcademicosAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_academica_actual', models.CharField(blank=True, default='ESCOM', max_length=100, null=True)),
                ('nom_programa_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('Completo', 'Tiempo Completo'), ('Parcial', 'Tiempo Parcial')], default='Completo', max_length=8, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabla de Datos Académicos',
                'verbose_name_plural': 'Tabla de Datos Académicos',
            },
        ),
        migrations.CreateModel(
            name='DatosAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabla de datos del asesor',
                'verbose_name_plural': 'Tabla de datos del asesores',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonalesAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=255, null=True)),
                ('colonia', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(blank=True, choices=[('H', 'H'), ('M', 'M')], default=None, max_length=1, null=True)),
                ('correo_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabla de Datos personales',
                'verbose_name_plural': 'Tabla de Datos personales',
            },
        ),
        migrations.CreateModel(
            name='ConstanciaProgramaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_creditos', models.FloatField(null=True)),
                ('fecha_limite', models.DateField(null=True)),
                ('firma_alumno', models.BooleanField()),
                ('firma_asesor', models.BooleanField()),
                ('firma_jefe', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosasesor')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
            options={
                'verbose_name': 'Constancia de inscripción al programa individual',
                'verbose_name_plural': 'Constancias de inscripción al programa individual',
            },
        ),
        migrations.CreateModel(
            name='ActaRevisionTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None)),
                ('titulo_tesis', models.CharField(max_length=255)),
                ('porcentaje_plagio', models.FloatField()),
                ('conclusion_plagio', models.TextField()),
                ('justificacion_conclusion', models.TextField()),
                ('manifiesto_comision', models.TextField(choices=[('Aprobar', 'Aprobar'), ('Susperder', 'Suspender'), ('No Aprobar', 'No Aprobar')], max_length=10)),
                ('firma_director_1', models.BooleanField(default=None)),
                ('firma_director_2', models.BooleanField(default=None)),
                ('firma_comision_1', models.BooleanField()),
                ('firma_comision_2', models.BooleanField()),
                ('firma_comision_3', models.BooleanField()),
                ('firma_presidente_colegio', models.BooleanField()),
                ('colegio_profesores', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formularios.colegioprofesoresposgrado')),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
            options={
                'verbose_name': 'Acta de Revisión de tesis',
                'verbose_name_plural': 'Actas de Revisión de tesis',
            },
        ),
        migrations.CreateModel(
            name='ActaRegistroTemaTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None, null=True)),
                ('tema_tesis', models.CharField(max_length=255)),
                ('objetivo_general_tesis', models.TextField()),
                ('nombre_director_1', models.CharField(max_length=100)),
                ('nombre_director_2', models.CharField(blank=True, max_length=100, null=True)),
                ('aplicacion_director', models.BooleanField()),
                ('base_tesis', models.TextField()),
                ('firma_director_1', models.BooleanField(blank=True, null=True)),
                ('firma_director_2', models.BooleanField(blank=True, null=True)),
                ('firma_alumno', models.BooleanField()),
                ('firma_presidente_colegio', models.BooleanField(blank=True, null=True)),
                ('colegio_profesores', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularios.colegioprofesoresposgrado')),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
            options={
                'verbose_name': 'Acta de Registro de Tema de Tesis',
                'verbose_name_plural': 'Actas de Registro de Tema de Tesis',
            },
        ),
        migrations.CreateModel(
            name='ConstanciaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_constancia_programa_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.constanciaprogramaindividual')),
                ('id_programa_actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.programaactividades')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_alumno', models.BooleanField(blank=True, null=True)),
                ('firma_asesor', models.BooleanField(blank=True, null=True)),
                ('asesor', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_jefe', models.BooleanField(blank=True, null=True)),
                ('jefe', models.CharField(blank=True, max_length=100, null=True)),
                ('aviso_privacidad', models.BooleanField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('datos_academicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
            options={
                'verbose_name': 'Solicitud de Inscripción',
                'verbose_name_plural': 'Solicitudes de Inscripción',
            },
        ),
        migrations.CreateModel(
            name='InscripcionAntecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_antecedentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.antecedentesacademicos')),
                ('id_solicitud_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.solicitudinscripcion')),
            ],
            options={
                'verbose_name': 'Tabla Solicitud de incripción - Antecedentes',
                'verbose_name_plural': 'Tabla Solicitudes de incripción - Antecedentes',
            },
        ),
        migrations.CreateModel(
            name='SolicitudReinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
                ('semestre_a_cursar', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('requiere_unidad', models.BooleanField()),
                ('firma_alumno', models.BooleanField()),
                ('firma_asesor', models.BooleanField(blank=True, null=True)),
                ('firma_jefe', models.BooleanField(blank=True, null=True)),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno')),
            ],
            options={
                'verbose_name': 'Solicitud de Reinscripción',
                'verbose_name_plural': 'Solicitudes de Reinscripción',
            },
        ),
    ]
