# Generated by Django 5.1.1 on 2024-10-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentesacademicos',
            name='fecha_graduacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
        migrations.DeleteModel(
            name='TipoSolicitud',
        ),
    ]
