# Generated by Django 5.1.1 on 2024-10-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentesacademicos',
            name='solicitud_inscripcion',
        ),
    ]
