# Generated by Django 5.1.1 on 2024-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaactividades',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='programaactividades',
            name='total_creditos',
        ),
        migrations.AddField(
            model_name='constanciaprogramaindividual',
            name='fecha_limite',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='constanciaprogramaindividual',
            name='total_creditos',
            field=models.FloatField(null=True),
        ),
    ]
