# Generated by Django 5.1.1 on 2024-11-02 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_remove_programaactividades_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaregistrotematesis',
            name='colegio_profesores',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularios.colegioprofesoresposgrado'),
        ),
        migrations.AddField(
            model_name='actaregistrotematesis',
            name='fecha',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='actarevisiontesis',
            name='colegio_profesores',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='formularios.colegioprofesoresposgrado'),
        ),
        migrations.AddField(
            model_name='colegioprofesoresposgrado',
            name='fecha_sesion',
            field=models.DateField(default=None),
        ),
    ]
