# Generated by Django 5.1.3 on 2025-01-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_remove_actaregistrotematesis_colegio_profesores_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcionantecedentes',
            options={'verbose_name': 'Solicitud de incripción - Antecedentes', 'verbose_name_plural': 'Tabla Solicitudes de incripción - Antecedentes'},
        ),
        migrations.AddField(
            model_name='datospersonalesalumno',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
