# Generated by Django 5.1.1 on 2024-10-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_remove_antecedentesacademicos_solicitud_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonalesalumno',
            name='firma_alumno',
        ),
    ]
