# Generated by Django 5.1.1 on 2024-10-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_remove_datospersonalesalumno_firma_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudinscripcion',
            name='aviso_privacidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinscripcion',
            name='firma_alumno',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinscripcion',
            name='firma_asesor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudinscripcion',
            name='firma_jefe',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
