# Generated by Django 5.1.3 on 2025-01-05 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_alter_inscripcionantecedentes_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreinscripcion',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_asesor_reinscripcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudreinscripcion',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_jefe_reinscripcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudinscripcion',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_asesor_inscripcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudinscripcion',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_jefe_inscripcion', to=settings.AUTH_USER_MODEL),
        ),
    ]
