# Generated by Django 5.1.1 on 2024-11-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_actaregistrotematesis_colegio_profesores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosacademicosalumno',
            name='estatus',
            field=models.CharField(blank=True, choices=[('Completo', 'Tiempo Completo'), ('Parcial', 'Tiempo Parcial')], default='Completo', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='datosacademicosalumno',
            name='unidad_academica_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
