# Generated by Django 5.1.3 on 2025-01-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_solicitudreinscripcion_asesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='firma_alumno',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='requiere_unidad',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
