# Generated by Django 5.1.3 on 2025-01-06 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_alter_solicitudreinscripcion_firma_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='datos_academicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularios.datosacademicosalumno'),
        ),
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='datos_personales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularios.datospersonalesalumno'),
        ),
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
