# Generated by Django 5.1.3 on 2025-01-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('formularios', '0006_alter_solicitudreinscripcion_datos_academicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaregistrotematesis',
            name='datos_academicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datosacademicosalumno'),
        ),
        migrations.AlterField(
            model_name='solicitudinscripcion',
            name='datos_academicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.datosacademicosalumno'),
        ),
        migrations.AlterField(
            model_name='constanciaprogramaindividual',
            name='datos_academicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datosacademicosalumno'),
        ),
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='datos_academicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.datosacademicosalumno'),
        ),
        migrations.AlterField(
            model_name='actarevisiontesis',
            name='datos_academicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datosacademicosalumno'),
        ),
        migrations.RemoveField(
            model_name='datospersonalesalumno',
            name='cuenta',
        ),
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='datos_personales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.datospersonalesalumno'),
        ),
        migrations.AlterField(
            model_name='solicitudinscripcion',
            name='datos_personales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.datospersonalesalumno'),
        ),
        migrations.AlterField(
            model_name='actarevisiontesis',
            name='datos_personales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datospersonalesalumno'),
        ),
        migrations.AlterField(
            model_name='constanciaprogramaindividual',
            name='datos_personales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datospersonalesalumno'),
        ),
        migrations.AlterField(
            model_name='actaregistrotematesis',
            name='datos_personales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datospersonalesalumno'),
        ),
        migrations.DeleteModel(
            name='DatosAcademicosAlumno',
        ),
        migrations.DeleteModel(
            name='DatosPersonalesAlumno',
        ),
    ]
