# Generated by Django 5.1.3 on 2024-11-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_rename_sexo_datospersonalesalumno_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='firma_asesor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='firma_jefe',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
