# Generated by Django 5.1.3 on 2024-11-29 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_alter_solicitudreinscripcion_firma_asesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaregistrotematesis',
            name='colegio_profesores',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularios.colegioprofesoresposgrado'),
        ),
        migrations.AlterField(
            model_name='actaregistrotematesis',
            name='firma_director_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actaregistrotematesis',
            name='firma_presidente_colegio',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
