# Generated by Django 5.1.3 on 2025-01-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_alter_constanciaprogramaindividual_asesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actarevisiontesis',
            name='colegio_profesores',
        ),
        migrations.RemoveField(
            model_name='actarevisiontesis',
            name='datos_academicos',
        ),
        migrations.RemoveField(
            model_name='actarevisiontesis',
            name='datos_personales',
        ),
        migrations.RemoveField(
            model_name='constanciaprograma',
            name='id_constancia_programa_individual',
        ),
        migrations.RemoveField(
            model_name='constanciaprograma',
            name='id_programa_actividades',
        ),
        migrations.RemoveField(
            model_name='constanciaprogramaindividual',
            name='total_creditos',
        ),
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='semestre_a_cursar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ActaRegistroTemaTesis',
        ),
        migrations.DeleteModel(
            name='ColegioProfesoresPosgrado',
        ),
        migrations.DeleteModel(
            name='ActaRevisionTesis',
        ),
        migrations.DeleteModel(
            name='ConstanciaPrograma',
        ),
        migrations.DeleteModel(
            name='ProgramaActividades',
        ),
    ]
