# Generated by Django 5.1.3 on 2025-01-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0010_alter_solicitudreinscripcion_semestre_a_cursar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreinscripcion',
            name='semestre_a_cursar',
            field=models.IntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True),
        ),
    ]
