# Generated by Django 5.1.3 on 2024-12-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_alter_programaactividades_unidad_aprendizaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actaregistrotematesis',
            options={'verbose_name': 'Acta de Registro de Tema de Tesis', 'verbose_name_plural': 'Actas de Registro de Tema de Tesis'},
        ),
        migrations.AlterModelOptions(
            name='actarevisiontesis',
            options={'verbose_name': 'Acta de Revision de tesis', 'verbose_name_plural': 'Actas de Revision de tesis'},
        ),
        migrations.AlterModelOptions(
            name='constanciaprogramaindividual',
            options={'verbose_name': 'Constancia de inscripción al programa individual', 'verbose_name_plural': 'Constancias de inscripción al programa individual'},
        ),
        migrations.AlterModelOptions(
            name='solicitudinscripcion',
            options={'verbose_name': 'Solicitud de Inscripción', 'verbose_name_plural': 'Solicitudes de Inscripción'},
        ),
        migrations.AlterModelOptions(
            name='solicitudreinscripcion',
            options={'verbose_name': 'Solicitud de Reinscripción', 'verbose_name_plural': 'Solicitudes de Reinscripción'},
        ),
    ]
