# Generated by Django 5.1.3 on 2024-12-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0012_alter_actaregistrotematesis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'verbose_name': 'Calendario', 'verbose_name_plural': 'Calendarios'},
        ),
        migrations.RenameField(
            model_name='datospersonalesalumno',
            old_name='domicilio',
            new_name='calle',
        ),
        migrations.AddField(
            model_name='datospersonalesalumno',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datospersonalesalumno',
            name='colonia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datospersonalesalumno',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datospersonalesalumno',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datospersonalesalumno',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datospersonalesalumno',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
