# Generated by Django 5.1.3 on 2024-12-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0013_alter_calendario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programasemestral',
            name='clave',
            field=models.CharField(choices=[('09B5786', '09B5786'), ('09B5787', '09B5787'), ('00000O1', '00000O1'), ('09B5789', '09B5789'), ('09B5791', '09B5791'), ('00000O2', '00000O2'), ('05B4670', '05B4670'), ('09B5792', '09B5792'), ('00000O3', '00000O3'), ('00000O4', '00000O4'), ('05B4670', '05B4670'), ('09B5794', '09B5794'), ('13A6641', '13A6641'), ('00TESIS', '00TESIS')], default='09B5786', max_length=7),
        ),
        migrations.AlterField(
            model_name='programasemestral',
            name='unidad_aprendizaje',
            field=models.CharField(choices=[('09B5786', 'Métodos matemáticos para el análisis de sistemas y señales'), ('09B5787', 'Fundamentos de comunicaciones móviles'), ('00000O1', 'Optativa I'), ('09B5789', 'Seminario I'), ('09B5791', 'Arquitectura de dispositivos móviles'), ('00000O2', 'Optativa II'), ('05B4670', 'Trabajo tesis'), ('09B5792', 'Seminario II'), ('00000O3', 'Optativa III'), ('00000O4', 'Optativa IV'), ('05B4670', 'Trabajo tesis'), ('09B5794', 'Seminario III'), ('13A6641', 'Seminario IV'), ('00TESIS', 'Tesis')], max_length=100),
        ),
    ]
