# Generated by Django 5.1.3 on 2024-12-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0015_solicitudinscripcion_asesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinscripcion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
