# Generated by Django 5.1.3 on 2024-12-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0016_solicitudinscripcion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programasemestral',
            name='clave',
            field=models.CharField(choices=[('09B5786', '09B5786'), ('09B5787', '09B5787'), ('000OPT1', '00000O1'), ('09B5789', '09B5789'), ('09B5791', '09B5791'), ('000OPT2', '00000O2'), ('05B4670', '05B4670'), ('09B5792', '09B5792'), ('000OPT3', '00000O3'), ('000OPT4', '00000O4'), ('05B4670', '05B4670'), ('09B5794', '09B5794'), ('13A6641', '13A6641'), ('00TESIS', '00TESIS')], default='09B5786', max_length=7),
        ),
        migrations.AlterField(
            model_name='programasemestral',
            name='unidad_aprendizaje',
            field=models.CharField(choices=[('Métodos matemáticos para el análisis de sistemas y señales', 'Métodos matemáticos para el análisis de sistemas y señales'), ('Fundamentos de comunicaciones móviles', 'Fundamentos de comunicaciones móviles'), ('Optativa I', 'Optativa I'), ('Seminario I', 'Seminario I'), ('Arquitectura de dispositivos móviles', 'Arquitectura de dispositivos móviles'), ('Optativa II', 'Optativa II'), ('Trabajo tesis', 'Trabajo tesis'), ('Seminario II', 'Seminario II'), ('Optativa III', 'Optativa III'), ('Optativa IV', 'Optativa IV'), ('Trabajo tesis', 'Trabajo tesis'), ('Seminario III', 'Seminario III'), ('Seminario IV', 'Seminario IV'), ('Tesis', 'Tesis')], max_length=100),
        ),
    ]
