# Generated by Django 5.1.3 on 2024-12-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0018_alter_programasemestral_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentesacademicos',
            name='institucion_donde_curso',
            field=models.CharField(default='ESCOM', max_length=255),
        ),
        migrations.AlterField(
            model_name='datosacademicosalumno',
            name='unidad_academica_actual',
            field=models.CharField(blank=True, default='ESCOM', max_length=100, null=True),
        ),
    ]
