# Generated by Django 5.1.3 on 2025-01-06 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAcademicosAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_academica_actual', models.CharField(blank=True, default='ESCOM', max_length=100, null=True)),
                ('nom_programa_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('Completo', 'Tiempo Completo'), ('Parcial', 'Tiempo Parcial')], default='Completo', max_length=8, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabla de Datos Académicos',
                'verbose_name_plural': 'Tabla de Datos Académicos',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonalesAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=255, null=True)),
                ('colonia', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(blank=True, choices=[('H', 'H'), ('M', 'M')], default=None, max_length=1, null=True)),
                ('correo_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabla de Datos personales',
                'verbose_name_plural': 'Tabla de Datos personales',
            },
        ),
    ]
