# Generated by Django 5.1.3 on 2025-01-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosacademicosalumno',
            options={'verbose_name': 'Datos Académicos', 'verbose_name_plural': 'Datos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='datospersonalesalumno',
            options={'verbose_name': 'Datos personales', 'verbose_name_plural': 'Datos personales'},
        ),
    ]
