# Generated by Django 5.1.3 on 2025-01-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColegioProfesoresPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_colegio_profesores', models.CharField(max_length=255)),
                ('nombre_sesion', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_sesion', models.IntegerField(blank=True, null=True)),
                ('fecha_sesion', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Tabla del colegio de profesores',
                'verbose_name_plural': 'Tabla del colegio de profesores',
            },
        ),
        migrations.CreateModel(
            name='ActaRegistroTemaTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None, null=True)),
                ('unidad_colegio_profesores', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_sesion', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_sesion', models.IntegerField(blank=True, null=True)),
                ('fecha_sesion', models.DateField(blank=True, default=None, null=True)),
                ('tema_tesis', models.CharField(max_length=255)),
                ('objetivo_general_tesis', models.TextField()),
                ('nombre_director_1', models.CharField(max_length=100)),
                ('nombre_director_2', models.CharField(blank=True, max_length=100, null=True)),
                ('aplicacion_director', models.BooleanField()),
                ('base_tesis', models.TextField()),
                ('firma_director_1', models.BooleanField(blank=True, null=True)),
                ('firma_director_2', models.BooleanField(blank=True, null=True)),
                ('firma_alumno', models.BooleanField()),
                ('firma_presidente_colegio', models.BooleanField(blank=True, null=True)),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datospersonalesalumno')),
            ],
            options={
                'verbose_name': 'Acta de Registro de Tema de Tesis',
                'verbose_name_plural': 'Actas de Registro de Tema de Tesis',
            },
        ),
        migrations.CreateModel(
            name='ActaRevisionTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None)),
                ('titulo_tesis', models.CharField(max_length=255)),
                ('porcentaje_plagio', models.FloatField()),
                ('conclusion_plagio', models.TextField()),
                ('justificacion_conclusion', models.TextField()),
                ('manifiesto_comision', models.TextField(choices=[('Aprobar', 'Aprobar'), ('Susperder', 'Suspender'), ('No Aprobar', 'No Aprobar')], max_length=10)),
                ('firma_director_1', models.BooleanField(default=None)),
                ('firma_director_2', models.BooleanField(default=None)),
                ('firma_comision_1', models.BooleanField()),
                ('firma_comision_2', models.BooleanField()),
                ('firma_comision_3', models.BooleanField()),
                ('firma_presidente_colegio', models.BooleanField()),
                ('datos_academicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datosacademicosalumno')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.datospersonalesalumno')),
                ('colegio_profesores', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tesis.colegioprofesoresposgrado')),
            ],
            options={
                'verbose_name': 'Acta de Revisión de tesis',
                'verbose_name_plural': 'Actas de Revisión de tesis',
            },
        ),
    ]
