# Generated by Django 5.1.3 on 2025-01-03 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=7)),
                ('unidad_aprendizaje', models.CharField(max_length=100)),
                ('creditos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unidad de aprendizaje',
                'verbose_name_plural': 'Unidades de aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='ProgramaSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_realizacion', models.CharField(default='ESCOM', max_length=255)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidad_aprendizaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programa.unidadaprendizaje')),
            ],
            options={
                'verbose_name': 'Unidad de aprendizaje',
                'verbose_name_plural': 'PROGRAMA SEMESTRAL',
            },
        ),
        migrations.CreateModel(
            name='InscripcionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitud_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.solicitudinscripcion')),
                ('id_programa_semestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.programasemestral')),
            ],
            options={
                'verbose_name': 'Tabla Solicitud de incripción - Antecedentes',
                'verbose_name_plural': 'Tabla Solicitudes de incripción - Programa',
            },
        ),
        migrations.CreateModel(
            name='ReinscripcionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_programa_semestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.programasemestral')),
                ('id_solicitud_reinscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.solicitudreinscripcion')),
            ],
        ),
    ]
