# Generated by Django 5.1.3 on 2025-01-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcionprograma',
            options={'verbose_name': 'Relación Solicitud de incripción - Programa', 'verbose_name_plural': 'Tabla Solicitudes de incripción - Programa'},
        ),
        migrations.AlterModelOptions(
            name='reinscripcionprograma',
            options={'verbose_name': 'Relación Solicitud de reincripción - Programa', 'verbose_name_plural': 'Tabla Solicitudes de reincripción - Programa'},
        ),
    ]
