# Generated by Django 5.1.3 on 2025-01-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_remove_actarevisiontesis_colegio_profesores_and_more'),
        ('programa', '0002_alter_inscripcionprograma_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_constancia_programa_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.constanciaprogramaindividual')),
                ('id_programa_actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.programasemestral')),
            ],
        ),
    ]
